# File specifying all processes that will start on hyprland startup

#################
### AUTOSTART ###
#################

exec-once = waybar & nm-applet 
exec-once = hyprpaper & 
exec-once = devmon
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
exec-once = wl-paste --primary --watch cliphist store

#################
### WALLPAPER ###
#################

exec-once = sleep 1 && ~/.config/hypr/change_wallpaper

###########################
### STARTING WORKSPACES ###
###########################

exec-once = [workspace 1 silent] alacritty --command tmux
exec-once = [workspace 2 silent] zen-browser
