general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock screen - discharging
listener {
    timeout = 120
    on-timeout = if [ "$(upower -i $(upower -e | grep 'BAT') | grep "state" | awk '{print $2}')" = "discharging" ]; then loginctl lock-session; fi
}

# Turn off screen - discharging
listener {
    timeout = 140
    on-timeout = if [ "$(upower -i $(upower -e | grep 'BAT') | grep "state" | awk '{print $2}')" = "discharging" ]; then hyprctl dispatch dpms off; fi
    on-resume = hyprctl dispatch dpms on
}

# Suspend the system - discharging
listener {
    timeout = 300
    on-timeout = if [ "$(upower -i $(upower -e | grep 'BAT') | grep "state" | awk '{print $2}')" = "discharging" ]; then systemctl suspend; fi
}

# Lock screen - charging
listener {
    timeout = 300
    on-timeout = if [ "$(upower -i $(upower -e | grep 'BAT') | grep "state" | awk '{print $2}')" = "charging" ]; then loginctl lock-session; fi
}

# Turn off screen - charging
listener {
    timeout = 360
    on-timeout = if [ "$(upower -i $(upower -e | grep 'BAT') | grep "state" | awk '{print $2}')" = "charging" ]; then hyprctl dispatch dpms off; fi
    on-resume = hyprctl dispatch dpms on
}

# Suspend the system - charging
listener {
    timeout = 600
    on-timeout = if [ "$(upower -i $(upower -e | grep 'BAT') | grep "state" | awk '{print $2}')" = "charging" ]; then systemctl suspend; fi
}
