# Main hyprland config file
# This file does not set any settings, it only imports other sources

source = ./hyprland/*
source = /home/dominik/.config/theme-manager/output/ocean/hyprland/auto-theme.conf
